### ISSUE TITLE
Why don't use Ansible best practice?

### ISSUE THREAD

**Issue by tzabbi** [dschier-wtd/fedora-homeserver#1]
Hey @dschier-wtd,

I am new to Ansible and like your project to learn Ansible! I find the page [Ansible best practice](https://docs.ansible.com/ansible/2.8/user_guide/playbooks_best_practices.html#best-practices) and wonder why you don't use this structure? Are there any reasons when I should use this structure and when not?

**Comment by dschier-wtd** [comment]
Hi,

thank you for the question. Let me explain this a bit.

The dedicated Ansible directory is needed to provide addtional scripts and kickstart files without cluttering the structure too much,

Storing the playbooks in a playbook directory is coming from the new collections structure and is also supported in the linked structures already. It just makes the ansible directory layout a bit more intuitive and there are less yml files next to each other that serve different purposes (requirements.yml for example).

Avoiding the inventory was a decision, since the idea of a single machine is easier to configure in a manifest. If you plan to setup many hosts a complex inventory layout makes way more sense.

Under the hood, I am sticking to this best practice: https://docs.ansible.com/ansible/2.8/user_guide/playbooks_best_practices.html#keep-it-simple

The current structure is easier to maintain, if you don't have any idea of Ansible and any experienced user can adapt it to their needs :)

**Comment by dschier-wtd** [comment]
If wanted, I can address this by providing an inventory and descriptions how to use it. I already have an article series about this and can add it, if wanted: https://blog.while-true-do.io/ansible-inventories-1/

**Comment by tzabbi** [comment]
Thanks a lot! I've read your blog and it was really informative. I'm a big fan of your blog!

Can't wait to read the next chapter of this homelab project.

**Comment by dschier-wtd** [comment]
Thank you a lot for the feedback, :) This week the virtualization part will be released, and the machine will become a lab, finally.
